### ISSUE TITLE
Use yarn

### ISSUE THREAD

**Issue by domoritz** [vega/editor-backend#6]
Instead of npm.

**Comment by algomaster99** [comment]
@domoritz I searched about both of them before choosing one of them. I chose `npm` because now it comes with a `lock` file support unlike its earlier versions and `npm` won't send package usage registry information to Facebook. Yarn is owned by facebook so it will.
Performance wise, both are equal. Still what do you suggest?

**Comment by domoritz** [comment]
I found yarn's performance to be much better and we are using yarn in all other Vega projects. I think we should switch all of them together if we want to do that.

**Comment by algomaster99** [comment]
@domoritz Okay, I will switch to `yarn`.

**Comment by algomaster99** [comment]
[This commit](https://github.com/vega/editor-backend/commit/ea40e71aba507fc8856fa087f4e498644d34df0d) closes this issue.

**Comment by domoritz** [comment]
In case you didn't know. You can just put `Fixes #6` in the commit message and Github will auto-close the issue.
